---
- name: set aws database host within the configuration
  lineinfile:
    dest=/etc/zabbix/zabbix_proxy.conf
    regexp="^DBHost="
    line="DBHost={{ zabbix_database_host }}"
  notify:
    - restart zabbix proxy
  tags:
    - zabbix
    - configuration
    - database

- name: ensure supporting ansible packages are installed for database management
  apt: name=python-psycopg2
  tags:
    - zabbix
    - database
    - package

- name: check if zabbix exists as database role
  sudo: yes
  sudo_user: postgres
  shell: "psql --command='\\dg' --host={{ zabbix_database_host|default('localhost') }} | grep -c zabbix"
  register: zabbix_database_roles
  ignore_errors: true
  tags:
    - zabbix
    - configuration
    - user
    - database

- name: create zabbix database role
  sudo: yes
  sudo_user: postgres
  shell: "psql --command=\"create role zabbix with password '{{ zabbix_database_password }}' login;\" --host={{ zabbix_database_host|default('localhost') }}"
  when: zabbix_database_roles.stdout == 0
  tags:
    - zabbix
    - configuration
    - user
    - database

- name: create database
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    login_host={{ zabbix_database_host }}
    name=zabbix
    owner=zabbix
    encoding=UTF-8
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8
    template=template0
  register: zabbix_database
  tags:
    - zabbix
    - setup
    - database

- name: stop local postgresql server
  service:
    name=postgresql
    state=stopped
  tags:
    - zabbix
    - database