---
- name: ensure supporting ansible packages are installed for database management
  action: apt name={{item}}
  with_items:
    - libpq-dev
    - python-psycopg2
  tags:
    - zabbix
    - database
    - package

- name: change local zabbix database user password
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    encrypted=no
    name=zabbix
    password={{ zabbix_database_password }}
  tags:
    - zabbix
    - configuration
    - user
    - database

- name: create local database
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name=zabbix
    owner=zabbix
    encoding=UTF-8
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8
    template=template0
  tags:
    - zabbix
    - setup
    - database