---
# Software installation
- name: download .deb file
  get_url:
    dest={{ temp_dir }}/zabbix-release_2.2-1+precise_all.deb
    url=http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+precise_all.deb
    mode=0644
  tags:
    - zabbix
    - packages

- name: install from .deb package
  command: dpkg --skip-same-version --install {{ temp_dir }}/zabbix-release_2.2-1+precise_all.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  tags:
    - zabbix
    - packages

- name: refreash apt cache
  apt: update_cache=yes
  when: dpkg_result|changed
  tags:
    - zabbix
    - packages

- include: postgresql.yml
  when: zabbix_database_type == "postgresql"
